import { InstallerInfo } from '../types/installer';

export const mockInstallers: InstallerInfo[] = [
  {
    id: 'vscode',
    name: 'Visual Studio Code',
    description: 'Powerful code editor from Microsoft with extension support',
    category: 'Development',
    installed: true,
    current_version: '1.85.1',
    latest_version: '1.86.0',
    can_update: true,
    dependencies: [],
    size: '95 MB',
    rating: 4.8,
    downloads: 45000000,
    last_updated: '2024-01-15',
    author: 'Microsoft',
    homepage: 'https://code.visualstudio.com',
    icon: 'https://code.visualstudio.com/favicon.ico',
  },
  {
    id: 'chrome',
    name: 'Google Chrome',
    description: 'Fast and secure browser from Google',
    category: 'Browsers',
    installed: true,
    current_version: '120.0.6099',
    latest_version: '120.0.6099',
    can_update: false,
    dependencies: [],
    size: '180 MB',
    rating: 4.6,
    downloads: 100000000,
    last_updated: '2024-01-10',
    author: 'Google LLC',
    homepage: 'https://www.google.com/chrome',
    icon: 'https://www.google.com/chrome/static/images/favicons/favicon-192x192.png',
  },
  {
    id: 'firefox',
    name: 'Mozilla Firefox',
    description: 'Free browser with focus on privacy',
    category: 'Browsers',
    installed: false,
    current_version: null,
    latest_version: '121.0',
    can_update: false,
    dependencies: [],
    size: '120 MB',
    rating: 4.7,
    downloads: 50000000,
    last_updated: '2024-01-12',
    author: 'Mozilla Foundation',
    homepage: 'https://www.mozilla.org/firefox',
    icon: 'https://www.mozilla.org/media/img/favicons/firefox/browser/favicon-196x196.59f382b0e087.png',
  },
  {
    id: 'nodejs',
    name: 'Node.js',
    description: 'JavaScript runtime built on V8',
    category: 'Development',
    installed: true,
    current_version: '20.10.0',
    latest_version: '20.11.0',
    can_update: true,
    dependencies: [],
    size: '35 MB',
    rating: 4.9,
    downloads: 25000000,
    last_updated: '2024-01-18',
    author: 'OpenJS Foundation',
    homepage: 'https://nodejs.org',
    icon: 'https://nodejs.org/static/images/favicons/favicon-32x32.png',
  },
  {
    id: 'git',
    name: 'Git',
    description: 'Distributed version control system',
    category: 'Development',
    installed: true,
    current_version: '2.43.0',
    latest_version: '2.43.0',
    can_update: false,
    dependencies: [],
    size: '45 MB',
    rating: 5.0,
    downloads: 30000000,
    last_updated: '2024-01-05',
    author: 'Git Community',
    homepage: 'https://git-scm.com',
    icon: 'https://git-scm.com/favicon.ico',
  },
  {
    id: 'docker',
    name: 'Docker Desktop',
    description: 'Platform for developing and running containerized applications',
    category: 'Development',
    installed: false,
    current_version: null,
    latest_version: '4.26.1',
    can_update: false,
    dependencies: ['wsl2'],
    size: '850 MB',
    rating: 4.5,
    downloads: 15000000,
    last_updated: '2024-01-14',
    author: 'Docker Inc',
    homepage: 'https://www.docker.com',
    icon: 'https://www.docker.com/favicon.ico',
  },
  {
    id: 'slack',
    name: 'Slack',
    description: 'Corporate messenger for team collaboration',
    category: 'Communication',
    installed: true,
    current_version: '4.35.126',
    latest_version: '4.36.134',
    can_update: true,
    dependencies: [],
    size: '165 MB',
    rating: 4.4,
    downloads: 20000000,
    last_updated: '2024-01-16',
    author: 'Slack Technologies',
    homepage: 'https://slack.com',
    icon: 'https://a.slack-edge.com/80588/marketing/img/icons/icon_slack_hash_colored.png',
  },
  {
    id: 'discord',
    name: 'Discord',
    description: 'Messenger for gaming and professional communication',
    category: 'Communication',
    installed: false,
    current_version: null,
    latest_version: '0.0.308',
    can_update: false,
    dependencies: [],
    size: '140 MB',
    rating: 4.6,
    downloads: 35000000,
    last_updated: '2024-01-11',
    author: 'Discord Inc',
    homepage: 'https://discord.com',
    icon: 'https://discord.com/assets/f9bb9c4af2b9c32a2c5ee0014661546d.png',
  },
  {
    id: 'postman',
    name: 'Postman',
    description: 'API platform for development and testing',
    category: 'Development',
    installed: false,
    current_version: null,
    latest_version: '10.21.6',
    can_update: false,
    dependencies: [],
    size: '215 MB',
    rating: 4.7,
    downloads: 12000000,
    last_updated: '2024-01-13',
    author: 'Postman Inc',
    homepage: 'https://www.postman.com',
    icon: 'https://www.postman.com/favicon-32x32.png',
  },
  {
    id: 'vlc',
    name: 'VLC Media Player',
    description: 'Universal media player with support for all formats',
    category: 'Media',
    installed: true,
    current_version: '3.0.20',
    latest_version: '3.0.20',
    can_update: false,
    dependencies: [],
    size: '95 MB',
    rating: 4.8,
    downloads: 60000000,
    last_updated: '2024-01-08',
    author: 'VideoLAN',
    homepage: 'https://www.videolan.org',
    icon: 'https://www.videolan.org/images/vlc-64.png',
  },
  {
    id: 'spotify',
    name: 'Spotify',
    description: 'Music streaming service',
    category: 'Media',
    installed: false,
    current_version: null,
    latest_version: '1.2.28',
    can_update: false,
    dependencies: [],
    size: '115 MB',
    rating: 4.5,
    downloads: 40000000,
    last_updated: '2024-01-17',
    author: 'Spotify AB',
    homepage: 'https://www.spotify.com',
    icon: 'https://open.spotify.com/favicon.ico',
  },
  {
    id: 'zoom',
    name: 'Zoom',
    description: 'Video conferencing platform',
    category: 'Communication',
    installed: true,
    current_version: '5.16.10',
    latest_version: '5.17.0',
    can_update: true,
    dependencies: [],
    size: '180 MB',
    rating: 4.3,
    downloads: 50000000,
    last_updated: '2024-01-19',
    author: 'Zoom Video Communications',
    homepage: 'https://zoom.us',
    icon: 'https://st1.zoom.us/zoom.ico',
  },
  {
    id: 'notion',
    name: 'Notion',
    description: 'Universal app for notes and organization',
    category: 'Productivity',
    installed: false,
    current_version: null,
    latest_version: '2.3.2',
    can_update: false,
    dependencies: [],
    size: '120 MB',
    rating: 4.7,
    downloads: 15000000,
    last_updated: '2024-01-09',
    author: 'Notion Labs Inc',
    homepage: 'https://www.notion.so',
    icon: 'https://www.notion.so/images/logo-ios.png',
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    description: 'App for creating knowledge base in Markdown',
    category: 'Productivity',
    installed: false,
    current_version: null,
    latest_version: '1.5.3',
    can_update: false,
    dependencies: [],
    size: '85 MB',
    rating: 4.9,
    downloads: 3000000,
    last_updated: '2024-01-14',
    author: 'Obsidian',
    homepage: 'https://obsidian.md',
    icon: 'https://obsidian.md/favicon.ico',
  },
  {
    id: 'gimp',
    name: 'GIMP',
    description: 'Free raster graphics editor',
    category: 'Graphics',
    installed: false,
    current_version: null,
    latest_version: '2.10.36',
    can_update: false,
    dependencies: [],
    size: '240 MB',
    rating: 4.4,
    downloads: 8000000,
    last_updated: '2024-01-06',
    author: 'GIMP Team',
    homepage: 'https://www.gimp.org',
    icon: 'https://www.gimp.org/images/favicon.png',
  },
  {
    id: 'inkscape',
    name: 'Inkscape',
    description: 'Professional vector graphics editor',
    category: 'Graphics',
    installed: false,
    current_version: null,
    latest_version: '1.3.2',
    can_update: false,
    dependencies: [],
    size: '310 MB',
    rating: 4.6,
    downloads: 5000000,
    last_updated: '2024-01-07',
    author: 'Inkscape Project',
    homepage: 'https://inkscape.org',
    icon: 'https://inkscape.org/favicon.ico',
  },
  {
    id: 'telegram',
    name: 'Telegram Desktop',
    description: 'Secure cloud messenger',
    category: 'Communication',
    installed: true,
    current_version: '4.14.9',
    latest_version: '4.14.9',
    can_update: false,
    dependencies: [],
    size: '85 MB',
    rating: 4.8,
    downloads: 70000000,
    last_updated: '2024-01-12',
    author: 'Telegram FZ-LLC',
    homepage: 'https://desktop.telegram.org',
    icon: 'https://telegram.org/favicon.ico',
  },
  {
    id: 'blender',
    name: 'Blender',
    description: '3D modeling, animation and rendering',
    category: 'Graphics',
    installed: false,
    current_version: null,
    latest_version: '4.0.2',
    can_update: false,
    dependencies: [],
    size: '450 MB',
    rating: 4.9,
    downloads: 12000000,
    last_updated: '2024-01-15',
    author: 'Blender Foundation',
    homepage: 'https://www.blender.org',
    icon: 'https://www.blender.org/favicon.ico',
  },
  {
    id: 'audacity',
    name: 'Audacity',
    description: 'Free audio editor',
    category: 'Media',
    installed: false,
    current_version: null,
    latest_version: '3.4.2',
    can_update: false,
    dependencies: [],
    size: '45 MB',
    rating: 4.5,
    downloads: 18000000,
    last_updated: '2024-01-04',
    author: 'Audacity Team',
    homepage: 'https://www.audacityteam.org',
    icon: 'https://www.audacityteam.org/favicon.ico',
  },
  {
    id: 'filezilla',
    name: 'FileZilla',
    description: 'FTP client for file transfer',
    category: 'Utilities',
    installed: false,
    current_version: null,
    latest_version: '3.66.4',
    can_update: false,
    dependencies: [],
    size: '25 MB',
    rating: 4.3,
    downloads: 10000000,
    last_updated: '2024-01-08',
    author: 'Tim Kosse',
    homepage: 'https://filezilla-project.org',
    icon: 'https://filezilla-project.org/favicon.ico',
  },
  {
    id: 'python',
    name: 'Python',
    description: 'High-level programming language',
    category: 'Development',
    installed: false,
    current_version: null,
    latest_version: '3.12.1',
    can_update: false,
    dependencies: [],
    size: '28 MB',
    rating: 4.9,
    downloads: 35000000,
    last_updated: '2024-01-20',
    author: 'Python Software Foundation',
    homepage: 'https://www.python.org',
    icon: 'https://www.python.org/favicon.ico',
  },
  {
    id: 'mysql',
    name: 'MySQL',
    description: 'Relational database management system',
    category: 'Development',
    installed: false,
    current_version: null,
    latest_version: '8.0.35',
    can_update: false,
    dependencies: [],
    size: '420 MB',
    rating: 4.6,
    downloads: 8000000,
    last_updated: '2024-01-03',
    author: 'Oracle Corporation',
    homepage: 'https://www.mysql.com',
    icon: 'https://www.mysql.com/favicon.ico',
  },
  {
    id: 'redis',
    name: 'Redis',
    description: 'In-memory database and cache',
    category: 'Development',
    installed: false,
    current_version: null,
    latest_version: '7.2.4',
    can_update: false,
    dependencies: [],
    size: '12 MB',
    rating: 4.8,
    downloads: 5000000,
    last_updated: '2024-01-11',
    author: 'Redis Ltd',
    homepage: 'https://redis.io',
    icon: 'https://redis.io/favicon.ico',
  },
  {
    id: 'pgadmin',
    name: 'pgAdmin',
    description: 'PostgreSQL administration and management',
    category: 'Development',
    installed: false,
    current_version: null,
    latest_version: '8.2',
    can_update: false,
    dependencies: ['postgresql'],
    size: '180 MB',
    rating: 4.4,
    downloads: 3000000,
    last_updated: '2024-01-07',
    author: 'pgAdmin Development Team',
    homepage: 'https://www.pgadmin.org',
    icon: 'https://www.pgadmin.org/favicon.ico',
  },
  {
    id: 'winrar',
    name: 'WinRAR',
    description: 'File archiver with RAR and ZIP support',
    category: 'Utilities',
    installed: true,
    current_version: '6.24',
    latest_version: '6.24',
    can_update: false,
    dependencies: [],
    size: '3.5 MB',
    rating: 4.2,
    downloads: 80000000,
    last_updated: '2024-01-02',
    author: 'win.rar GmbH',
    homepage: 'https://www.win-rar.com',
    icon: 'https://www.win-rar.com/favicon.ico',
  },
  {
    id: '7zip',
    name: '7-Zip',
    description: 'Free archiver with high compression ratio',
    category: 'Utilities',
    installed: false,
    current_version: null,
    latest_version: '23.01',
    can_update: false,
    dependencies: [],
    size: '1.5 MB',
    rating: 4.8,
    downloads: 90000000,
    last_updated: '2024-01-01',
    author: 'Igor Pavlov',
    homepage: 'https://www.7-zip.org',
    icon: 'https://www.7-zip.org/favicon.ico',
  },
  {
    id: 'notepadpp',
    name: 'Notepad++',
    description: 'Advanced text editor for Windows',
    category: 'Utilities',
    installed: true,
    current_version: '8.6.1',
    latest_version: '8.6.2',
    can_update: true,
    dependencies: [],
    size: '4.2 MB',
    rating: 4.7,
    downloads: 60000000,
    last_updated: '2024-01-16',
    author: 'Don Ho',
    homepage: 'https://notepad-plus-plus.org',
    icon: 'https://notepad-plus-plus.org/favicon.ico',
  },
  {
    id: 'jetbrains-idea',
    name: 'IntelliJ IDEA',
    description: 'Integrated development environment for Java and Kotlin',
    category: 'Development',
    installed: false,
    current_version: null,
    latest_version: '2023.3.2',
    can_update: false,
    dependencies: ['jdk'],
    size: '980 MB',
    rating: 4.9,
    downloads: 8000000,
    last_updated: '2024-01-18',
    author: 'JetBrains',
    homepage: 'https://www.jetbrains.com/idea',
    icon: 'https://www.jetbrains.com/favicon-32x32.png',
  },
  {
    id: 'sublime-text',
    name: 'Sublime Text',
    description: 'Elegant text editor for code',
    category: 'Development',
    installed: false,
    current_version: null,
    latest_version: '4.0',
    can_update: false,
    dependencies: [],
    size: '22 MB',
    rating: 4.6,
    downloads: 15000000,
    last_updated: '2024-01-09',
    author: 'Sublime HQ',
    homepage: 'https://www.sublimetext.com',
    icon: 'https://www.sublimetext.com/favicon.ico',
  },
  {
    id: 'teamviewer',
    name: 'TeamViewer',
    description: 'Remote access and support',
    category: 'Utilities',
    installed: false,
    current_version: null,
    latest_version: '15.50.5',
    can_update: false,
    dependencies: [],
    size: '48 MB',
    rating: 4.1,
    downloads: 25000000,
    last_updated: '2024-01-13',
    author: 'TeamViewer Germany GmbH',
    homepage: 'https://www.teamviewer.com',
    icon: 'https://www.teamviewer.com/favicon.ico',
  },
];
